version: '3'

services:
  # MongoDB: https://hub.docker.com/_/mongo
  mongo:
    image: mongo:5.0.13
    networks:
      - graylog
  
  # Elasticsearch: https://hub.docker.com/_/elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  
  # Graylog: https://hub.docker.com/r/graylog/graylog
  graylog:
    image: graylog/graylog:5.0
    environment:
      # CHANGE ME (must be at least 16 chars)
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Default password is 'admin' with SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      # My password is 'osmanaliyardim'
      - GRAYLOG_ROOT_PASSWORD_SHA2=5312a502798467f3ae3cd0935cece6e4872533fb97fa43efb1ac4865b8039034
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 -- /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # Graylog web ui and rest api
      - 9000:9000
      # Syslog TCP
      - 1514:1514
      # Syslog UDP
      - 1514:1514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
networks:
  graylog:
    driver: bridge
